version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/scraper"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "blixten85"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "docker"
    directory: "/scraper"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "blixten85"
    labels:
      - "dependencies"
      - "github-actions"
